version: "3"
services:
  challenge:
    build: .
    image: challenge_2023_n1ctf_web_ignite
    tty: true
    ports:
    - 10000:10000
    restart: always
    environment:
    - FLAG=ctfhub{test_flag}
    - DOMAIN=test.sandbox.ctfhub.com
