[package]
name = "emulator"
version = "0.1.0"
authors = ["hxp", "Joonas Javanainen <joonas.javanainen@gmail.com>"]
edition = "2021"

[dependencies]
mooneye-gb-core = { path = "mooneye-gb/core" }

anyhow = "1.0.45"
clap = "3.0.0-beta.5"
glium = "0.30.2"
nalgebra = "0.29.0"
serde = { version = "1.0.130", features = ["derive"]}
bincode = "1.3.3"
flate2 = "1.0.22"
drawille = "0.3.0"
ctrlc = "3.2.1"
parking_lot = "0.11.1"
base64 = "0.13.0"
gif = "0.11.3"

[workspace]
