[package]
name = "hash-brownie-recipes"
version = "0.1.0"
authors = ["@ScepticCtf"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashbrown = "<=0.12.2"
