[package]
name = "thirty-twodle-challenge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
cc = "1.1.31"

[dependencies]
anyhow = "1.0.86"
lazy_static = "1.4.0"
