version: "3.9"
services:
  geotask:
    build: .
    ports:
      - "127.0.0.1:8002:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
