version: "2.4"
services:
    pwn_note:
        privileged: true
        build: ./
        image: n1ctf_2022_note
        pull_policy: never
        ports:
            - "11451:8888"
        expose:
            - "8888"
        restart: unless-stopped
