[package]
name = "stg_compiler_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stg_compiler = { path = "../stg_compiler" }
syn = "*"
quote = "*"
bincode = "*"
