[package]
name = "checker"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0.89", features = ["full", "fold"] }
quote = "1.0.16"
proc-macro2 = "1.0.36"

[lib]
name = "checker"
path = "src/lib.rs"
proc-macro = true
