services:
  uwsgi:
    build: ./app
    environment:
      TZ: "Asia/Tokyo"
    expose:
      - "7777"
    restart: always
  nginx:
    build: ./nginx
    links:
      - uwsgi
    ports:
      - "31415:80"
    environment:
      TZ: "Asia/Tokyo"
    restart: always
