services:
  redis:
    container_name: redis
    image: "redis:6-alpine"

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - FLAG=EPFL{FAKE_FLAG}
    depends_on:
      - redis
    ports:
      - "1337:8080"

  bot:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile.bot
    depends_on:
      - redis
