version: '3'

services:
  stack:
    build: ./
    volumes:
      - ./share:/home/STACK:ro
      - ./xinetd:/etc/xinetd.d/stack:ro
    ports:
      - "10101:10101"
    expose:
      - "10101"
    restart: always
